# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.4.1
# LVGL version: 8.3.6
# Project name: SquareLine_Project

import lvgl as lv
import ui_images
import ui_events

dispp = lv.disp_get_default()
theme = lv.theme_default_init(dispp, lv.palette_main(lv.PALETTE.BLUE), lv.palette_main(lv.PALETTE.RED), False, lv.font_default())
dispp.set_theme(theme)

#font_CN = lv.font_load("A:ui_font_CN.bin")

def ui_theme_set(idx):
   return

def SetFlag( obj, flag, value):
    if (value):
        obj.add_flag(flag)
    else:
        obj.clear_flag(flag)
    return

_ui_comp_table = {}
_ui_comp_prev = None
_ui_name_prev = None
_ui_child_prev = None
_ui_comp_table.clear()

def _ui_comp_del_event(e):
    target = e.get_target()
    _ui_comp_table[id(target)].remove()

def ui_comp_get_child(comp, child_name):
    return _ui_comp_table[id(comp)][child_name]

def ui_comp_get_root_from_child(child, compname):
    for component in _ui_comp_table:
        if _ui_comp_table[component]["_CompName"]==compname:
            for part in _ui_comp_table[component]:
                if id(_ui_comp_table[component][part]) == id(child):
                    return _ui_comp_table[component]
    return None
def SetBarProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def SetPanelProperty(target, id, val):
   if id == 'Position_X': target.set_x(val)
   if id == 'Position_Y': target.set_y(val)
   if id == 'Width': target.set_width(val)
   if id == 'Height': target.set_height(val)
   return

def SetDropdownProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val)
   return

def SetImageProperty(target, id, val, val2):
   if id == 'Image': target.set_src(val)
   if id == 'Angle': target.set_angle(val2)
   if id == 'Zoom': target.set_zoom(val2)
   return

def SetLabelProperty(target, id, val):
   if id == 'Text': target.set_text(val)
   return

def SetRollerProperty(target, id, val):
   if id == 'Selected':
      target.set_selected(val, lv.ANIM.OFF)
   if id == 'Selected_with_anim':
      target.set_selected(val, lv.ANIM.ON)
   return

def SetSliderProperty(target, id, val):
   if id == 'Value_with_anim': target.set_value(val, lv.ANIM.ON)
   if id == 'Value': target.set_value(val, lv.ANIM.OFF)
   return

def ChangeScreen( src, fademode, speed, delay):
    lv.scr_load_anim(src, fademode, speed, delay, False)
    return

def DeleteScreen(src):
    return

def IncrementArc( trg, val):
    trg.set_value(trg.get_value()+val)
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def IncrementBar( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    return

def IncrementSlider( trg, val, anim):
    trg.set_value(trg.get_value()+val,anim)
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def KeyboardSetTarget( keyboard, textarea):
    keyboard.set_textarea(textarea)
    return

def ModifyFlag( obj, flag, value):
    if (value=="TOGGLE"):
        if ( obj.has_flag(flag) ):
            obj.clear_flag(flag)
        else:
            obj.add_flag(flag)
        return

    if (value=="ADD"):
        obj.add_flag(flag)
    else:
        obj.clear_flag(flag)
    return

def ModifyState( obj, state, value):
    if (value=="TOGGLE"):
        if ( obj.has_state(state) ):
            obj.clear_state(state)
        else:
            obj.add_state(state)
        return

    if (value=="ADD"):
        obj.add_state(state)
    else:
        obj.clear_state(state)
    return

def TextAreaMoveCursor( trg, val):
    if val=="UP" : trg.cursor_up()
    if val=="RIGHT" : trg.cursor_right()
    if val=="DOWN" : trg.cursor_down()
    if val=="LEFT" : trg.cursor_left()
    trg.add_state(lv.STATE.FOCUSED)
    return

def set_opacity(obj, v):
    obj.set_style_opa(v, lv.STATE.DEFAULT|lv.PART.MAIN)
    return

def SetTextValueArc( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueSlider( trg, src, prefix, postfix):
    trg.set_text(prefix+str(src.get_value())+postfix)
    return

def SetTextValueChecked( trg, src, txton, txtoff):
    if src.has_state(lv.STATE.CHECKED):
        trg.set_text(txton)
    else:
        trg.set_text(txtoff)
    return

def StepSpinbox( trg, val):
    if val==1 : trg.increment()
    if val==-1 : trg.decrement()
    lv.event_send(trg,lv.EVENT.VALUE_CHANGED, None)
    return

def SwitchTheme(val):
    ui_theme_set(val)
    return

# COMPONENTS

 # COMPONENT Image1
def ui_Image1_create(comp_parent):
    cui_Image1 = lv.img(comp_parent)
    cui_Image1.set_src(ui_images.TemporaryImage)
    cui_Image1.set_width(lv.SIZE.CONTENT)	# 1
    cui_Image1.set_height(lv.SIZE.CONTENT)   # 1
    cui_Image1.set_align( lv.ALIGN.CENTER)
    SetFlag(cui_Image1, lv.obj.FLAG.ADV_HITTEST, True)
    SetFlag(cui_Image1, lv.obj.FLAG.SCROLLABLE, False)
    _ui_comp_table[id(cui_Image1)]= {"Image1" : cui_Image1, "_CompName" : "Image1"}
    return cui_Image1

ui____initial_actions0 = lv.obj()

def Label1_eventhandler(event_struct):
   target = event_struct.get_target()
   event = event_struct.code
   if event == lv.EVENT.CLICKED and True:
      saveFenToLocal( event_struct )
   return

def Button2_eventhandler(event_struct):
   target = event_struct.get_target()
   event = event_struct.code
   if event == lv.EVENT.CLICKED and True:
      writeMessage( event_struct )
   return

def write_data(message):
    # 向命名管道写入数据
    try:
        with open('/tmp/mypipe1', 'w') as pipe:
            pipe.write(message + '\n')
            pipe.flush()  # 确保数据写入管道
            print(f"Message sent: {message}")
    except OSError as e:
        print("Error writing to pipe:", e)

def write_data2(message):
    # 向命名管道写入数据
    try:
        with open('/tmp/mypipe2', 'w') as pipe:
            pipe.write(message + '\n')
            pipe.flush()  # 确保数据写入管道
            print(f"Message sent: {message}")
    except OSError as e:
        print("Error writing to pipe:", e)

def write_data3(message):
    # 向命名管道写入数据
    try:
        with open('/tmp/mypipe4', 'w') as pipe:
            pipe.write(message + '\n')
            pipe.flush()  # 确保数据写入管道
            print(f"Message sent: {message}")
    except OSError as e:
        print("Error writing to pipe:", e)
        
def writeMessage(event_struct):
    write_data2('message')

def showGo(go_data):
	if go_data=='1':
		print('receive 1')
		SetFlag(ui_Label4, lv.obj.FLAG.HIDDEN, False)
	if go_data=='0':
		print('receive 0')
		SetFlag(ui_Label4, lv.obj.FLAG.HIDDEN, True)

def backGo(back_data):
	if back_data=='1':
		SetFlag(ui_Label5, lv.obj.FLAG.HIDDEN, False)
	if back_data=='0':
		SetFlag(ui_Label5, lv.obj.FLAG.HIDDEN, True)

def modelChange(event_struct):

    # 定义缓冲区大小
    BUF_SIZE = 32
    global ui_Spinner1, ui_Spinner3
    # 获取目标对象（即滚轮对象）
    roller = event_struct.get_target()

    # 创建一个缓冲区并获取选中的字符串
    buf = bytearray(BUF_SIZE)
    roller.get_selected_str(buf, BUF_SIZE)
    
    # 将缓冲区转换为字符串进行比较
    selected_str = buf.decode("utf-8").strip('\x00')  # 移除空字节
    
    # 检查是否选中了“同步”
    if selected_str == "同步":
    	print('同步模式')
	SetFlag(ui_Spinner1, lv.obj.FLAG.HIDDEN, True)
	SetFlag(ui_Spinner3, lv.obj.FLAG.HIDDEN, True)
	SetFlag(ui_TabView2, lv.obj.FLAG.HIDDEN, True)
	SetFlag(ui_Button2, lv.obj.FLAG.HIDDEN, True)

    if selected_str == "最佳选点":
    	print('最佳选点模式')
	SetFlag(ui_Spinner1, lv.obj.FLAG.HIDDEN, False)
	SetFlag(ui_Spinner3, lv.obj.FLAG.HIDDEN, False)
	SetFlag(ui_Button2, lv.obj.FLAG.HIDDEN, True)
	SetFlag(ui_TabView2, lv.obj.FLAG.HIDDEN, True)
	write_data('bestpoint')    
    if selected_str == "大语言模型":
    	print('大语言模型模式')
	SetFlag(ui_Spinner1, lv.obj.FLAG.HIDDEN, False)
	SetFlag(ui_Spinner3, lv.obj.FLAG.HIDDEN, False)
	SetFlag(ui_Button2, lv.obj.FLAG.HIDDEN, False)
	SetFlag(ui_TabView2, lv.obj.FLAG.HIDDEN, False)
	write_data('analysis')
   
def Roller1_eventhandler(event_struct):
   target = event_struct.get_target()
   event = event_struct.code
   if event == lv.EVENT.VALUE_CHANGED and True:
      modelChange( event_struct )
   return

def Dropdown1_eventhandler(event_struct):
   target = event_struct.get_target()
   event = event_struct.code
   if event == lv.EVENT.VALUE_CHANGED and True:
      chooseLevel( event_struct )
   return

ui_Screen1 = lv.obj()
SetFlag(ui_Screen1, lv.obj.FLAG.SCROLLABLE, False)

ui_Image2 = lv.img(ui_Screen1)
ui_Image2.set_src(ui_images.ui_img_qipan_png)
ui_Image2.set_width(lv.SIZE.CONTENT)	# 1
ui_Image2.set_height(lv.SIZE.CONTENT)   # 1
ui_Image2.set_x(9)
ui_Image2.set_y(44)
ui_Image2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Image2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_Image2, lv.obj.FLAG.SCROLLABLE, False)
ui_Image2.set_zoom(440)

ui_Image1 = lv.img(ui_Screen1)
ui_Image1.set_src(ui_images.ui_img_xiangqidark_png)
ui_Image1.set_width(lv.SIZE.CONTENT)	# 1
ui_Image1.set_height(lv.SIZE.CONTENT)   # 1
ui_Image1.set_x(-220)
ui_Image1.set_y(0)
ui_Image1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Image1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_Image1, lv.obj.FLAG.SCROLLABLE, False)
ui_Image1.set_zoom(180)

ui_ba1 = lv.img(ui_Screen1)
ui_ba1.set_src(ui_images.ui_img_black_advisor_png)
ui_ba1.set_width(lv.SIZE.CONTENT)	# 1
ui_ba1.set_height(lv.SIZE.CONTENT)   # 1
ui_ba1.set_x(-290)
ui_ba1.set_y(-315)
ui_ba1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ba1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_ba1, lv.obj.FLAG.SCROLLABLE, False)
ui_ba1.set_zoom(200)

ui_bc2 = lv.img(ui_Screen1)
ui_bc2.set_src(ui_images.ui_img_black_cannon_png)
ui_bc2.set_width(lv.SIZE.CONTENT)	# 92
ui_bc2.set_height(lv.SIZE.CONTENT)   # 92
ui_bc2.set_x(-10)
ui_bc2.set_y(-175)
ui_bc2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bc2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bc2, lv.obj.FLAG.SCROLLABLE, False)
ui_bc2.set_zoom(200)

ui_br2 = lv.img(ui_Screen1)
ui_br2.set_src(ui_images.ui_img_black_chariot_png)
ui_br2.set_width(lv.SIZE.CONTENT)	# 92
ui_br2.set_height(lv.SIZE.CONTENT)   # 92
ui_br2.set_x(60)
ui_br2.set_y(-315)
ui_br2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_br2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_br2, lv.obj.FLAG.SCROLLABLE, False)
ui_br2.set_zoom(200)

ui_bb2 = lv.img(ui_Screen1)
ui_bb2.set_src(ui_images.ui_img_black_elephant_png)
ui_bb2.set_width(lv.SIZE.CONTENT)	# 92
ui_bb2.set_height(lv.SIZE.CONTENT)   # 92
ui_bb2.set_x(-80)
ui_bb2.set_y(-315)
ui_bb2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bb2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bb2, lv.obj.FLAG.SCROLLABLE, False)
ui_bb2.set_zoom(200)

ui_ba2 = lv.img(ui_Screen1)
ui_ba2.set_src(ui_images.ui_img_black_advisor_png)
ui_ba2.set_width(lv.SIZE.CONTENT)	# 92
ui_ba2.set_height(lv.SIZE.CONTENT)   # 92
ui_ba2.set_x(-150)
ui_ba2.set_y(-315)
ui_ba2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ba2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_ba2, lv.obj.FLAG.SCROLLABLE, False)
ui_ba2.set_zoom(200)

ui_bn2 = lv.img(ui_Screen1)
ui_bn2.set_src(ui_images.ui_img_black_horse_png)
ui_bn2.set_width(lv.SIZE.CONTENT)	# 92
ui_bn2.set_height(lv.SIZE.CONTENT)   # 92
ui_bn2.set_x(-10)
ui_bn2.set_y(-315)
ui_bn2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bn2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bn2, lv.obj.FLAG.SCROLLABLE, False)
ui_bn2.set_zoom(200)

ui_bc1 = lv.img(ui_Screen1)
ui_bc1.set_src(ui_images.ui_img_black_cannon_png)
ui_bc1.set_width(lv.SIZE.CONTENT)	# 92
ui_bc1.set_height(lv.SIZE.CONTENT)   # 92
ui_bc1.set_x(-430)
ui_bc1.set_y(-175)
ui_bc1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bc1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bc1, lv.obj.FLAG.SCROLLABLE, False)
ui_bc1.set_zoom(200)

ui_bk1 = lv.img(ui_Screen1)
ui_bk1.set_src(ui_images.ui_img_black_king_png)
ui_bk1.set_width(lv.SIZE.CONTENT)	# 92
ui_bk1.set_height(lv.SIZE.CONTENT)   # 92
ui_bk1.set_x(-220)
ui_bk1.set_y(-315)
ui_bk1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bk1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bk1, lv.obj.FLAG.SCROLLABLE, False)
ui_bk1.set_zoom(200)

ui_bp5 = lv.img(ui_Screen1)
ui_bp5.set_src(ui_images.ui_img_black_pawn_png)
ui_bp5.set_width(lv.SIZE.CONTENT)	# 92
ui_bp5.set_height(lv.SIZE.CONTENT)   # 92
ui_bp5.set_x(60)
ui_bp5.set_y(-105)
ui_bp5.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bp5, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bp5, lv.obj.FLAG.SCROLLABLE, False)
ui_bp5.set_zoom(200)

ui_bp4 = lv.img(ui_Screen1)
ui_bp4.set_src(ui_images.ui_img_black_pawn_png)
ui_bp4.set_width(lv.SIZE.CONTENT)	# 92
ui_bp4.set_height(lv.SIZE.CONTENT)   # 92
ui_bp4.set_x(-80)
ui_bp4.set_y(-105)
ui_bp4.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bp4, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bp4, lv.obj.FLAG.SCROLLABLE, False)
ui_bp4.set_zoom(200)

ui_bp3 = lv.img(ui_Screen1)
ui_bp3.set_src(ui_images.ui_img_black_pawn_png)
ui_bp3.set_width(lv.SIZE.CONTENT)	# 92
ui_bp3.set_height(lv.SIZE.CONTENT)   # 92
ui_bp3.set_x(-220)
ui_bp3.set_y(-105)
ui_bp3.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bp3, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bp3, lv.obj.FLAG.SCROLLABLE, False)
ui_bp3.set_zoom(200)

ui_bp2 = lv.img(ui_Screen1)
ui_bp2.set_src(ui_images.ui_img_black_pawn_png)
ui_bp2.set_width(lv.SIZE.CONTENT)	# 92
ui_bp2.set_height(lv.SIZE.CONTENT)   # 92
ui_bp2.set_x(-500)
ui_bp2.set_y(-105)
ui_bp2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bp2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bp2, lv.obj.FLAG.SCROLLABLE, False)
ui_bp2.set_zoom(200)

ui_bp1 = lv.img(ui_Screen1)
ui_bp1.set_src(ui_images.ui_img_black_pawn_png)
ui_bp1.set_width(lv.SIZE.CONTENT)	# 92
ui_bp1.set_height(lv.SIZE.CONTENT)   # 92
ui_bp1.set_x(-360)
ui_bp1.set_y(-105)
ui_bp1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bp1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bp1, lv.obj.FLAG.SCROLLABLE, False)
ui_bp1.set_zoom(200)

ui_ra2 = lv.img(ui_Screen1)
ui_ra2.set_src(ui_images.ui_img_red_advisor_png)
ui_ra2.set_width(lv.SIZE.CONTENT)	# 92
ui_ra2.set_height(lv.SIZE.CONTENT)   # 92
ui_ra2.set_x(-150)
ui_ra2.set_y(315)
ui_ra2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ra2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_ra2, lv.obj.FLAG.SCROLLABLE, False)
ui_ra2.set_zoom(200)

ui_rk1 = lv.img(ui_Screen1)
ui_rk1.set_src(ui_images.ui_img_red_king_png)
ui_rk1.set_width(lv.SIZE.CONTENT)	# 92
ui_rk1.set_height(lv.SIZE.CONTENT)   # 92
ui_rk1.set_x(-220)
ui_rk1.set_y(315)
ui_rk1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rk1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rk1, lv.obj.FLAG.SCROLLABLE, False)
ui_rk1.set_zoom(200)

ui_rc2 = lv.img(ui_Screen1)
ui_rc2.set_src(ui_images.ui_img_red_cannon_png)
ui_rc2.set_width(lv.SIZE.CONTENT)	# 92
ui_rc2.set_height(lv.SIZE.CONTENT)   # 92
ui_rc2.set_x(-10)
ui_rc2.set_y(175)
ui_rc2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rc2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rc2, lv.obj.FLAG.SCROLLABLE, False)
ui_rc2.set_zoom(200)

ui_rc1 = lv.img(ui_Screen1)
ui_rc1.set_src(ui_images.ui_img_red_cannon_png)
ui_rc1.set_width(lv.SIZE.CONTENT)	# 92
ui_rc1.set_height(lv.SIZE.CONTENT)   # 92
ui_rc1.set_x(-430)
ui_rc1.set_y(175)
ui_rc1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rc1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rc1, lv.obj.FLAG.SCROLLABLE, False)
ui_rc1.set_zoom(200)

ui_bb1 = lv.img(ui_Screen1)
ui_bb1.set_src(ui_images.ui_img_black_elephant_png)
ui_bb1.set_width(lv.SIZE.CONTENT)	# 92
ui_bb1.set_height(lv.SIZE.CONTENT)   # 92
ui_bb1.set_x(-360)
ui_bb1.set_y(-315)
ui_bb1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bb1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bb1, lv.obj.FLAG.SCROLLABLE, False)
ui_bb1.set_zoom(200)

ui_bn1 = lv.img(ui_Screen1)
ui_bn1.set_src(ui_images.ui_img_black_horse_png)
ui_bn1.set_width(lv.SIZE.CONTENT)	# 92
ui_bn1.set_height(lv.SIZE.CONTENT)   # 92
ui_bn1.set_x(-430)
ui_bn1.set_y(-315)
ui_bn1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_bn1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_bn1, lv.obj.FLAG.SCROLLABLE, False)
ui_bn1.set_zoom(200)

ui_br1 = lv.img(ui_Screen1)
ui_br1.set_src(ui_images.ui_img_black_chariot_png)
ui_br1.set_width(lv.SIZE.CONTENT)	# 92
ui_br1.set_height(lv.SIZE.CONTENT)   # 92
ui_br1.set_x(-500)
ui_br1.set_y(-315)
ui_br1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_br1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_br1, lv.obj.FLAG.SCROLLABLE, False)
ui_br1.set_zoom(200)

ui_ra1 = lv.img(ui_Screen1)
ui_ra1.set_src(ui_images.ui_img_red_advisor_png)
ui_ra1.set_width(lv.SIZE.CONTENT)	# 92
ui_ra1.set_height(lv.SIZE.CONTENT)   # 92
ui_ra1.set_x(-290)
ui_ra1.set_y(315)
ui_ra1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_ra1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_ra1, lv.obj.FLAG.SCROLLABLE, False)
ui_ra1.set_zoom(200)

ui_rb2 = lv.img(ui_Screen1)
ui_rb2.set_src(ui_images.ui_img_red_elephant_png)
ui_rb2.set_width(lv.SIZE.CONTENT)	# 92
ui_rb2.set_height(lv.SIZE.CONTENT)   # 92
ui_rb2.set_x(-80)
ui_rb2.set_y(315)
ui_rb2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rb2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rb2, lv.obj.FLAG.SCROLLABLE, False)
ui_rb2.set_zoom(200)

ui_rp4 = lv.img(ui_Screen1)
ui_rp4.set_src(ui_images.ui_img_red_pawn_png)
ui_rp4.set_width(lv.SIZE.CONTENT)	# 92
ui_rp4.set_height(lv.SIZE.CONTENT)   # 92
ui_rp4.set_x(-80)
ui_rp4.set_y(105)
ui_rp4.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rp4, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rp4, lv.obj.FLAG.SCROLLABLE, False)
ui_rp4.set_zoom(200)

ui_rp5 = lv.img(ui_Screen1)
ui_rp5.set_src(ui_images.ui_img_red_pawn_png)
ui_rp5.set_width(lv.SIZE.CONTENT)	# 92
ui_rp5.set_height(lv.SIZE.CONTENT)   # 92
ui_rp5.set_x(60)
ui_rp5.set_y(105)
ui_rp5.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rp5, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rp5, lv.obj.FLAG.SCROLLABLE, False)
ui_rp5.set_zoom(200)

ui_rn2 = lv.img(ui_Screen1)
ui_rn2.set_src(ui_images.ui_img_red_horse_png)
ui_rn2.set_width(lv.SIZE.CONTENT)	# 92
ui_rn2.set_height(lv.SIZE.CONTENT)   # 92
ui_rn2.set_x(-10)
ui_rn2.set_y(315)
ui_rn2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rn2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rn2, lv.obj.FLAG.SCROLLABLE, False)
ui_rn2.set_zoom(200)

ui_rr2 = lv.img(ui_Screen1)
ui_rr2.set_src(ui_images.ui_img_red_chariot_png)
ui_rr2.set_width(lv.SIZE.CONTENT)	# 92
ui_rr2.set_height(lv.SIZE.CONTENT)   # 92
ui_rr2.set_x(60)
ui_rr2.set_y(315)
ui_rr2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rr2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rr2, lv.obj.FLAG.SCROLLABLE, False)
ui_rr2.set_zoom(200)

ui_rr1 = lv.img(ui_Screen1)
ui_rr1.set_src(ui_images.ui_img_red_chariot_png)
ui_rr1.set_width(lv.SIZE.CONTENT)	# 92
ui_rr1.set_height(lv.SIZE.CONTENT)   # 92
ui_rr1.set_x(-500)
ui_rr1.set_y(315)
ui_rr1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rr1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rr1, lv.obj.FLAG.SCROLLABLE, False)
ui_rr1.set_zoom(200)

ui_rb1 = lv.img(ui_Screen1)
ui_rb1.set_src(ui_images.ui_img_red_elephant_png)
ui_rb1.set_width(lv.SIZE.CONTENT)	# 92
ui_rb1.set_height(lv.SIZE.CONTENT)   # 92
ui_rb1.set_x(-360)
ui_rb1.set_y(315)
ui_rb1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rb1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rb1, lv.obj.FLAG.SCROLLABLE, False)
ui_rb1.set_zoom(200)

ui_rp3 = lv.img(ui_Screen1)
ui_rp3.set_src(ui_images.ui_img_red_pawn_png)
ui_rp3.set_width(lv.SIZE.CONTENT)	# 92
ui_rp3.set_height(lv.SIZE.CONTENT)   # 92
ui_rp3.set_x(-220)
ui_rp3.set_y(105)
ui_rp3.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rp3, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rp3, lv.obj.FLAG.SCROLLABLE, False)
ui_rp3.set_zoom(200)

ui_rn1 = lv.img(ui_Screen1)
ui_rn1.set_src(ui_images.ui_img_red_horse_png)
ui_rn1.set_width(lv.SIZE.CONTENT)	# 92
ui_rn1.set_height(lv.SIZE.CONTENT)   # 92
ui_rn1.set_x(-430)
ui_rn1.set_y(315)
ui_rn1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rn1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rn1, lv.obj.FLAG.SCROLLABLE, False)
ui_rn1.set_zoom(200)

ui_rp2 = lv.img(ui_Screen1)
ui_rp2.set_src(ui_images.ui_img_red_pawn_png)
ui_rp2.set_width(lv.SIZE.CONTENT)	# 92
ui_rp2.set_height(lv.SIZE.CONTENT)   # 92
ui_rp2.set_x(-360)
ui_rp2.set_y(105)
ui_rp2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rp2, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rp2, lv.obj.FLAG.SCROLLABLE, False)
ui_rp2.set_zoom(200)

ui_rp1 = lv.img(ui_Screen1)
ui_rp1.set_src(ui_images.ui_img_red_pawn_png)
ui_rp1.set_width(lv.SIZE.CONTENT)	# 92
ui_rp1.set_height(lv.SIZE.CONTENT)   # 92
ui_rp1.set_x(-500)
ui_rp1.set_y(105)
ui_rp1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_rp1, lv.obj.FLAG.ADV_HITTEST, True)
SetFlag(ui_rp1, lv.obj.FLAG.SCROLLABLE, False)
ui_rp1.set_zoom(200)

ui_Button1 = lv.btn(ui_Screen1)
ui_Button1.set_width(128)
ui_Button1.set_height(50)
ui_Button1.set_x(480)
ui_Button1.set_y(-287)
ui_Button1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Button1, lv.obj.FLAG.HIDDEN, True)

ui_Label1 = lv.label(ui_Button1)
ui_Label1.set_text("Save")
ui_Label1.set_width(lv.SIZE.CONTENT)	# 1
ui_Label1.set_height(lv.SIZE.CONTENT)   # 1
ui_Label1.set_align( lv.ALIGN.CENTER)
ui_Label1.set_style_text_font( lv.font_montserrat_16, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Label1.add_event_cb(Label1_eventhandler, lv.EVENT.ALL, None)
ui_Spinner1 = lv.spinner(ui_Screen1, 1000, 90)
ui_Spinner1.set_width(65)
ui_Spinner1.set_height(65)
ui_Spinner1.set_x(-10)
ui_Spinner1.set_y(175)
ui_Spinner1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Spinner1, lv.obj.FLAG.HIDDEN, True)
ui_Spinner1.set_style_blend_mode( lv.BLEND_MODE.NORMAL, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Spinner1.set_style_arc_color(lv.color_hex(0x3DFA1B), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Spinner1.set_style_arc_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Spinner1.set_style_arc_width( 6, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Spinner3 = lv.spinner(ui_Screen1, 1000, 90)
ui_Spinner3.set_width(65)
ui_Spinner3.set_height(65)
ui_Spinner3.set_x(-220)
ui_Spinner3.set_y(175)
ui_Spinner3.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Spinner3, lv.obj.FLAG.HIDDEN, True)
ui_Spinner3.set_style_blend_mode( lv.BLEND_MODE.NORMAL, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Spinner3.set_style_opa( 188, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Spinner3.set_style_arc_color(lv.color_hex(0xFD0000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Spinner3.set_style_arc_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_TabView2 = lv.tabview(ui_Screen1, lv.DIR.TOP, 50)
ui_TabView2.set_width(481)
ui_TabView2.set_height(422)
ui_TabView2.set_x(377)
ui_TabView2.set_y(66)
ui_TabView2.set_align( lv.ALIGN.CENTER)

ui_TabPage1 = (ui_TabView2).add_tab("大语言模型分析")

ui_Label3 = lv.label(ui_TabPage1)
ui_Label3.set_text("")
ui_Label3.set_width(lv.SIZE.CONTENT)	# 1
ui_Label3.set_height(lv.SIZE.CONTENT)   # 1
#ui_Label3.set_style_text_font( font_CN, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Button2 = lv.btn(ui_Screen1)
ui_Button2.set_width(100)
ui_Button2.set_height(50)
ui_Button2.set_x(496)
ui_Button2.set_y(-203)
ui_Button2.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Button2, lv.obj.FLAG.HIDDEN, True)

ui_Label4 = lv.label(ui_Button2)
ui_Label4.set_text("分析")
ui_Label4.set_width(lv.SIZE.CONTENT)	# 1
ui_Label4.set_height(lv.SIZE.CONTENT)   # 1
ui_Label4.set_align( lv.ALIGN.CENTER)
#ui_Label4.set_style_text_font( font_CN, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Button2.add_event_cb(Button2_eventhandler, lv.EVENT.ALL, None)
ui_Roller1 = lv.roller(ui_Screen1)
ui_Roller1.set_options("同步\n最佳选点\n大语言模型", lv.roller.MODE.INFINITE)
ui_Roller1.set_selected(0,lv.ANIM.OFF) # need update when change: 同步\n最佳选点\n大语言模型
ui_Roller1.set_height(136)
ui_Roller1.set_width(lv.SIZE.CONTENT)	# 1
ui_Roller1.set_x(243)
ui_Roller1.set_y(-219)
ui_Roller1.set_align( lv.ALIGN.CENTER)
#ui_Roller1.set_style_text_font( font_CN, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Roller1.set_style_bg_color(lv.color_hex(0x0C0101), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Roller1.set_style_bg_opa(0, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Roller1.set_style_bg_grad_color(lv.color_hex(0xB6ACAC), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Roller1.set_style_border_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Roller1.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Roller1.set_style_text_color(lv.color_hex(0xFD0808), lv.PART.SELECTED | lv.STATE.DEFAULT )
ui_Roller1.set_style_text_opa(255, lv.PART.SELECTED| lv.STATE.DEFAULT )

ui_Roller1.add_event_cb(Roller1_eventhandler, lv.EVENT.ALL, None)
ui_Label2 = lv.label(ui_Screen1)
ui_Label2.set_text("欢迎来到象棋的世界")
ui_Label2.set_width(lv.SIZE.CONTENT)	# 1
ui_Label2.set_height(lv.SIZE.CONTENT)   # 1
ui_Label2.set_x(381)
ui_Label2.set_y(-309)
ui_Label2.set_align( lv.ALIGN.CENTER)
ui_Label2.set_style_text_color(lv.color_hex(0xF206FE), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Label2.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
#ui_Label2.set_style_text_font( font_CN, lv.PART.MAIN | lv.STATE.DEFAULT )

lv.scr_load(ui_Screen1)


ui_Dropdown1 = lv.dropdown(ui_Screen1)
ui_Dropdown1.set_options("Level 1\nLevel 2\nLevel 3")
ui_Dropdown1.set_width(150)
ui_Dropdown1.set_height(lv.SIZE.CONTENT)   # 1
ui_Dropdown1.set_x(479)
ui_Dropdown1.set_y(-267)
ui_Dropdown1.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Dropdown1, lv.obj.FLAG.SCROLL_ON_FOCUS, True)
ui_Dropdown1.set_style_text_font( lv.font_montserrat_16, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Dropdown1.add_event_cb(Dropdown1_eventhandler, lv.EVENT.ALL, None)


ui_Label4 = lv.label(ui_Screen1)
ui_Label4.set_text("请玩家落子")
ui_Label4.set_width(lv.SIZE.CONTENT)	# 1
ui_Label4.set_height(lv.SIZE.CONTENT)   # 1
ui_Label4.set_x(-221)
ui_Label4.set_y(0)
ui_Label4.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Label4, lv.obj.FLAG.HIDDEN, True)
ui_Label4.set_style_text_color(lv.color_hex(0x06F40E), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Label4.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Label4.set_style_bg_color(lv.color_hex(0xFFE820), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Label4.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Label5 = lv.label(ui_Screen1)
ui_Label5.set_text("当前行棋非法，请手动归位")
ui_Label5.set_width(lv.SIZE.CONTENT)	# 1
ui_Label5.set_height(lv.SIZE.CONTENT)   # 1
ui_Label5.set_x(-222)
ui_Label5.set_y(0)
ui_Label5.set_align( lv.ALIGN.CENTER)
SetFlag(ui_Label5, lv.obj.FLAG.HIDDEN, True)
ui_Label5.set_style_text_color(lv.color_hex(0xFC0000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Label5.set_style_text_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Label5.set_style_bg_color(lv.color_hex(0xFDFF01), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Label5.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

def updateMessage(message_data):
	ui_Label3.set_text(message_data)
	
def chooseLevel(event_struct):
	obj = event_struct.get_target()
        selected_option = obj.get_selected()
        selected_text = obj.get_options().split("\n")[selected_option]	
        if selected_text == 'Level 1':
            print("Option 1 selected")
            write_data3('setoption name Skill Level value 0')
        elif selected_text == 'Level 2':
            print("Option 2 selected")
            write_data3('setoption name Skill Level value 4')
        elif selected_text == 'Level 3':
            print("Option 3 selected")
            write_data3('setoption name Skill Level value 8')	
	elif selected_text == 'Level 4':
            print("Option 3 selected")
            write_data3('setoption name Skill Level value 12')
	elif selected_text == 'Level 5':
            print("Option 3 selected")
            write_data3('setoption name Skill Level value 16')
	elif selected_text == 'Level EX':
            print("Option 3 selected")
            write_data3('setoption name Skill Level value 20')       
                 

	
def update_chess_pieces_from_fen(fen):
    """
    根据FEN字符串更新棋子的位置和可见性
    """
    # 棋子位置定义（仅用作参考）
    positions = {
        'br1': (-500, -315), 'bn1': (-430, -315), 'bb1': (-360, -315),
        'ba1': (-290, -315), 'bk1': (-220, -315), 'ba2': (-150, -315),
        'bb2': (-80, -315), 'bn2': (-10, -315), 'br2': (60, -315),
        'bc1': (-430, -175), 'bc2': (-10, -175), 'bp1': (-500, -105),
        'bp2': (-354, -105), 'bp3': (-220, -105), 'bp4': (-80, -105),
        'bp5': (60, -105), 'rr1': (-500, 315), 'rn1': (-430, 315),
        'rb1': (-360, 315), 'ra1': (-290, 315), 'rk1': (-220, 315),
        'ra2': (-150, 315), 'rb2': (-80, 315), 'rn2': (-10, 315),
        'rr2': (60, 315), 'rc1': (-430, 175), 'rc2': (-10, 175),
        'rp1': (-500, 105), 'rp2': (-360, 105), 'rp3': (-220, 105),
        'rp4': (-80, 105), 'rp5': (60, 105)
    }

    # 将所有棋子设置为隐藏
    for piece in positions:
        SetFlag(globals()[f'ui_' + piece], lv.obj.FLAG.HIDDEN, True)

    # FEN字符到棋子类型的映射
    fen_to_piece = {
        'r': 'br', 'n': 'bn', 'b': 'bb', 'a': 'ba', 'k': 'bk', 'c': 'bc', 'p': 'bp',
        'R': 'rr', 'N': 'rn', 'B': 'rb', 'A': 'ra', 'K': 'rk', 'C': 'rc', 'P': 'rp'
    }

    # 记录每种棋子的使用情况
    piece_count = {k: 1 for k in fen_to_piece.values()}

    # 棋盘格子的大小
    grid_width = 70
    grid_height = 70

    # 拆分FEN字符串并获取棋子和spinner位置
    fen_parts = fen.split(' ', 1)  # 限制split只分割第一个空格
    fen_rows = fen_parts[0].split('/')

    # 确保我们有足够的部分来提取spinner位置
    if len(fen_parts) > 1:
        spinner_positions = fen_parts[1].strip()  # 提取spinner位置
    else:
        spinner_positions = ""

    # 输出调试信息
    print(f"FEN parts: {fen_parts}")
    print(f"Spinner positions: {spinner_positions}")

    # 映射FEN字符串到棋盘
    for y, row in enumerate(fen_rows):
        x = 0
        for char in row:
            if char.isdigit():
                x += int(char)  # 空格
            else:
                piece = fen_to_piece[char]
                piece_number = piece_count[piece]
                piece_name = f'{piece}{piece_number}'
                piece_count[piece] += 1

                if piece_name in positions:
                    ui_piece = globals()[f'ui_{piece_name}']
                    SetFlag(ui_piece, lv.obj.FLAG.HIDDEN, False)
                    SetFlag(ui_piece, lv.obj.FLAG.SCROLLABLE, False)
                    # 使用正确的格子大小计算棋子位置
                    ui_piece.set_x(-500 + x * grid_width)
                    ui_piece.set_y(-315 + y * grid_height)
                x += 1

    # 更新spinner位置
    if len(spinner_positions) == 4:
        # 解析spinner位置
        spinner1_row = int(spinner_positions[0])  # Use as-is
        spinner1_col = int(spinner_positions[1])  # Use as-is
        spinner3_row = int(spinner_positions[2])  # Use as-is
        spinner3_col = int(spinner_positions[3])  # Use as-is

        print(f"Parsed Spinner1 position: Row {spinner1_row}, Col {spinner1_col}")
        print(f"Parsed Spinner3 position: Row {spinner3_row}, Col {spinner3_col}")

        # spinner1位置计算
        ui_Spinner1.set_x(-500 + spinner1_col * grid_width)
        ui_Spinner1.set_y(-315 + spinner1_row * grid_height)

        # spinner3位置计算
        ui_Spinner3.set_x(-500 + spinner3_col * grid_width)
        ui_Spinner3.set_y(-315 + spinner3_row * grid_height)

    else:
        print("Spinner positions are not correctly formatted or missing.")

    # 载入界面
    lv.scr_load(ui_Screen1)

